---

lxc_container_backing_store: dir

# Tempest is being configured to use a known network
tempest_public_subnet_cidr: 10.0.248.0/26

# This makes running neutron in a distributed system easier and a lot less noisy
neutron_l2_population: True

# This makes the glance image store use swift instead of the file backend
glance_default_store: swift

{% if http_proxy is defined and http_proxy %}
proxy_env_url: "{{ http_proxy }}"

{% if global_environment_variables is defined and global_environment_variables | bool %}
{% raw %}
no_proxy_env: "localhost,127.0.0.1,{{ internal_lb_vip_address }},{{ external_lb_vip_address }},{% for host in groups['all_containers'] %}{{ hostvars[host]['container_address'] }}{% if not loop.last %},{% endif %}{% endfor %}"
global_environment_variables:
  HTTP_PROXY: "{{ proxy_env_url }}"
  HTTPS_PROXY: "{{ proxy_env_url }}"
  NO_PROXY: "{{ no_proxy_env }}"
  http_proxy: "{{ proxy_env_url }}"
  https_proxy: "{{ proxy_env_url }}"
  no_proxy: "{{ no_proxy_env }}"
{% endraw %}
{% endif %}

{% if deployment_environment_variables is defined and deployment_environment_variables | bool %}
{% raw %}
deployment_environment_variables:
  http_proxy: "{{ proxy_env_url }}"
  https_proxy: "{{ proxy_env_url }}"
  no_proxy: "localhost,127.0.0.1,{{ internal_lb_vip_address }},{{ external_lb_vip_address }},{% for host in groups['keystone_all'] %}{{ hostvars[host]['container_address'] }}{% if not loop.last %},{% endif %}{% endfor %}"
{% endraw %}
{% endif %}

glance_glance_api_conf_overrides:
  glance_store:
    http_proxy_information: "http:http://, https:http://"
{% endif %}
