---
# Copyright 2016, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Update neutron security bindings variables
  hosts: localhost
  connection: local
  gather_facts: false
  user: root
  tasks:
      - fail:
          msg: >
            neutron_ml2_conf_ini_overrides is defined in one of your overrides files but
            neutron_ml2_conf_ini_overrides.ml2.extension_drivers is unset. Please set
            neutron_ml2_conf_ini_overrides.ml2.extension_drivers = '' to prevent
            https://bugs.launchpad.net/neutron/+bug/1509312
        when:
          - neutron_ml2_conf_ini_overrides is defined
          - "'extension_drivers' not in (neutron_ml2_conf_ini_overrides.ml2 | default({}))"
      - name: Disable the port security driver
        # The below is not ideal, but it preserves whatever was in the
        # user_variables file without clobbering comments or having an
        # additional script.
        lineinfile:
            dest: /etc/openstack_deploy/user_variables.yml
            line: "neutron_ml2_conf_ini_overrides:\n  ml2:\n    extension_drivers: ''"
        when:
          - neutron_ml2_conf_ini_overrides is not defined
